---
title: "Estimating EWAC coefficients"
output: 
  html_notebook: 
    code_folding: hide
bibliography: bibliography.bib
---

# Introduction


# Methods




# Results


This notebook estimates and stores coefficients to apply to the Extended AUDIT-C schedule in order to compute an estimator of the weekly alcohol consumption (EWAC) in UK units (8g or 10mL of pure alcohol).


```{r}
source("../01_src/functions.R")
source("../01_src/filepaths.R")
library(data.table)
library(tidyverse)
load(file.path(atsfiles, "qfmodule.RData"))


ats_small <- ats %>% 
  transmute(.,
    gf = gfmeanweekly, 
    AF = case_when(
      audit1_label == "Never" ~ 1.0,
      audit1_label == "Monthly or less" ~ 2.0,
      audit1_label == "2 to 4 times a month" ~ 3.0,
      audit1_label == "2 to 3 times a week" ~ 4.0,
      audit1_label == "4 to 5 times a week" ~ 5.0,
      audit1_label == "6 or more times a week" ~ 6.0,
      TRUE ~ as.numeric(NA)
    ), 
    AQ = case_when(
      audit2_label == "1 to 2" ~ 1.0,
      audit2_label == "3 to 4" ~ 2.0,
      audit2_label == "5 to 6" ~ 3.0,
      audit2_label == "7 to 9" ~ 4.0,
      audit2_label == "10 to 12" ~ 5.0,
      audit2_label == "13 to 15" ~ 6.0,
      audit2_label == "16 or more" ~ 7.0,
      TRUE ~ as.numeric(NA)
    ), 
    AV = case_when(
      audit3_label == "Never" ~ 1.0,
      audit3_label == "Less than monthly" ~ 2.0,
      audit3_label == "Monthly" ~ 3.0,
      audit3_label == "Daily or almost daily" ~ 4.0,
      TRUE ~ as.numeric(NA)
    )) %>% 
  na.omit() %>% 
  mutate(
    AF = factor(AF),
    AQ = factor(AQ),
    AV = factor(AV)
  )







```


```{r}

m3 <- lm(log(gfmeanweekly + .5) ~  factor(audit1) + factor(audit2) -1,
         data = ats)
exp(summary(m3)$coef)


```


